version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "./"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: "chore(deps): "
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "./client"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: "chore(deps): "
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "./server"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: "chore(deps): "
    labels:
      - "dependencies"
